### ISSUE TITLE
Add `DeleteWatch` in Cache

### ISSUE THREAD

**Issue by jessicayuen** [envoyproxy/xds-relay#57]
When onCancel is called from go-control-plane to the Orchestrator, Orchestrator removes management of this watch, but the watch persists in the Cache until the TTL expires. We could more effectively manage resources if a DeleteWatch(req *v2.DiscoveryRequest) function existed.

**Comment by LisaLudique** [comment]
[lrucache](https://godoc.org/github.com/golang/groupcache/lru) doesn't expose a way to easily iterate over the cache entries. We could maintain a list of all the keys for this purpose.
