### ISSUE TITLE
Add support for stats

### ISSUE THREAD

**Issue by jyotimahapatra** [envoyproxy/xds-relay#61]
Few xdsclient tests could benefit from adding a stat framework and assert on those. 
ref: https://github.com/envoyproxy/xds-relay/pull/46#discussion_r410393519

**Comment by jyotimahapatra** [comment]
ref: https://github.com/envoyproxy/xds-relay/pull/37

**Comment by eapolinario** [comment]
Implemented in https://github.com/envoyproxy/xds-relay/pull/87.
