### ISSUE TITLE
Implement State-of-the-world xDS cache API

### ISSUE THREAD

**Issue by jessicayuen** [envoyproxy/xds-relay#9]
Refer to the tech spec on [Cache](https://docs.google.com/document/d/1X9fFzqBZzrSmx2d0NkmjDW2tc8ysbLQS9LaRQRxdJZU/edit#heading=h.e7gk6wgvxz9d).

xDS Relay will maintain its own in-memory cache to keep the most recent response given the aggregated key.

Each key will maintain the following fields:
- _resp_: the most recent discovery response from the control plane
- _watchers_: The open watches (requests) awaiting a response.
- _stream_open_: Identifies whether there is already a connection open with go-control-plane for this aggregated key. If the value is false, the first request will be propagated to the control plane.

Implement Cache interface and API for the state-of-the-world xDS Requests. This is a proposed set of APIs.
```
Exists(key: string): bool
- Return false if the key exists.

Fetch(key: string): *v3.Response
- Return the cached response if it exists, otherwise nil.

IsStreamOpen(key: string): bool
- Return false if no stream is opened against the upstream control plane for the given key.

SetStreamOpen(open: bool)
- Sets whether there is a stream open against the upstream control plane.

Set(resp: v3.Response, key: string): ([]*v3.Request, err)
- Set the cache response and return the list of open watches.

Clear(key: string)
- Discards the existing watches. This is meant to be used in tangent with the API above.

Set(req: v3.Request, key: string): (bool, err)
- Adds the watch to the cache. Returns whether a stream is open.
```

**Comment by LisaLudique** [comment]
Exists should return true if the key exists, right?

**Comment by jessicayuen** [comment]
> Exists should return true if the key exists, right?
yes! typo.

Feel free to modify these API suggestions as you see fit. I would primarily consider the sequence diagram in https://docs.google.com/document/d/1X9fFzqBZzrSmx2d0NkmjDW2tc8ysbLQS9LaRQRxdJZU/edit#heading=h.1g62tk7rs8tn, to make sure the cache interface allows for the request manager to issue this workflow.
